version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"

  web:
    build: .
    working_dir: /app
    # Run as root initially to fix permissions
    user: root
    depends_on:
      - redis
    command: >
      bash -c "mkdir -p /app/data/db /app/data/csv /app/app/static &&
               chmod -R 777 /app/data &&
               python manage.py makemigrations &&
               python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               gunicorn core.wsgi:application --bind 0.0.0.0:8000 --log-level debug --access-logfile - --error-logfile -"
    volumes:
      - .:/app:delegated
      - static_volume:/app/staticfiles
      - ./data:/app/data
    ports:
      - "8040:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
      - SECRET_KEY=your-secret-key-here
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AD_IMAGE_URL=https://levelcrossads.srshti.co.in/Blue%20And%20White%20Modern%20Dental%20Clinic%20Poster.webp
      - TOP_AD_IMAGE_URL=https://levelcrossads.srshti.co.in/banner1.webp
      - MIDDLE_AD_IMAGE_URL_1=https://levelcrossads.srshti.co.in/banner.webp
      - MIDDLE_AD_IMAGE_URL_2=https://levelcrossads.srshti.co.in/banner.webp
      - MIDDLE_AD_IMAGE_URL_3=https://levelcrossads.srshti.co.in/banner.webp
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    restart: always

  celery_worker:
    build: .
    working_dir: /app
    user: root 
    depends_on:
      - web
      - redis
    command: >
      bash -c "chmod -R 777 /app/data &&
               python -m celery -A core worker --loglevel=info"
    volumes:
      - .:/app:delegated
      - static_volume:/app/staticfiles
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always

  celery_beat:
    build: .
    working_dir: /app
    user: root
    depends_on:
      - web
      - redis
    command: >
      bash -c "chmod -R 777 /app/data &&
               python manage.py migrate django_celery_beat &&
               python manage.py migrate --noinput &&
               python -m celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app:delegated
      - static_volume:/app/staticfiles
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always

volumes:
  static_volume:

