version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               gunicorn core.wsgi:application --bind 0.0.0.0:8000 --log-level debug --access-logfile - --error-logfile -"
    volumes:
      - ./data/levelcross_django/csv:/app/data/csv  # For uploaded CSV files
      - ./data/levelcross_django/db:/app/data/db  # For SQLite database
    ports:
      - "8024:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
      - SECRET_KEY=your-secret-key-here
      - PYTHONUNBUFFERED=1
      - AD_IMAGE_URL=https://levelcrossads.srshti.co.in/Blue%20And%20White%20Modern%20Dental%20Clinic%20Poster.webp
      - TOP_AD_IMAGE_URL=https://levelcrossads.srshti.co.in/banner1.webp
      - MIDDLE_AD_IMAGE_URL_1=https://levelcrossads.srshti.co.in/banner.webp
      - MIDDLE_AD_IMAGE_URL_2=https://levelcrossads.srshti.co.in/banner.webp
      - MIDDLE_AD_IMAGE_URL_3=https://levelcrossads.srshti.co.in/banner.webp
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    restart: always

