# Generated by Django 5.1.6 on 2025-02-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('station', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('week_day', models.CharField(help_text="Comma-separated days or 'All'", max_length=50)),
                ('weekly', models.CharField(blank=True, max_length=50)),
                ('day_reach_station', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('ERS-SRT', 'ERS to SRT'), ('SRT-ERS', 'SRT to ERS')], default='ERS-SRT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CrossedTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossed_date', models.DateField(auto_now_add=True)),
                ('crossed_time', models.TimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.train')),
            ],
            options={
                'unique_together': {('train', 'crossed_date')},
            },
        ),
    ]
