# Generated by Django 5.1.6 on 2025-02-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_station', models.CharField(max_length=200)),
                ('status_as_of', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delay', models.IntegerField(default=0)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.train')),
            ],
            options={
                'get_latest_by': 'last_update',
            },
        ),
    ]
