# Generated by Django 5.1.6 on 2025-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstatus',
            name='passed_ezhupunna',
            field=models.BooleanField(default=False),
        ),
    ]
