# Generated by Django 5.1.6 on 2025-02-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trainstatus_passed_ezhupunna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainstatus',
            name='passed_ezhupunna',
        ),
    ]
