# Generated by Django 5.1.6 on 2025-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_trainstatus_passed_ezhupunna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.CharField(max_length=10),
        ),
    ]
