# Generated by Django 4.2.20 on 2025-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_train_train_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
